### ISSUE TITLE
Wrong display of organisation/reference names

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#219] opened 2018-10-19 08:44 UTC
If the user performs a search at either /organisations or /references, and then removes the filter, the resulting list does not show the names for the annotations, just the IDs.

**Comment by nomoregrapes** [comment] 2018-10-19 10:33
I think I have solved this, and names are showing on production where previously they weren't.

Several references still show their ID, but when you click them the reference/page doesn't exist. The reason they show in results, I think is caused by #218. We could keep this ticket open until I've fixed that.

**Comment by peterwebster** [comment] 2018-10-19 11:33
@nomoregrapes should it be fixed on test then? On this page https://henson-test.durham.ac.uk/?page=3&search_field=only_organisations both items 26 and 27 (one showing correctly, one not) have broken links

**Comment by peterwebster** [comment] 2018-11-07 13:18
This is still an issue on test:  see https://henson-test.durham.ac.uk/?utf8=%E2%9C%93&search_field=only_organisations&q=Oxford and then remove the filter.

**Comment by peterwebster** [comment] 2018-11-13 14:46
@nomoregrapes this seems now to be fixed on test, probably as a result of the Solr issue we discussed. Is there any reason to keep it open until it is fixed on production? As it seems to be not an issue in itself but an artefact of the Solr issue, perhaps not?

**Comment by nomoregrapes** [comment] 2018-11-13 15:51
It makes sense that this would be connected to the Solr issue. Closing the ticket.

**Closed as completed by nomoregrapes** 2018-11-13 15:51 UTC
Labels: Dev Phase 2, bug fix
