### ISSUE TITLE
Implement revised formatting rules for publications (<ref )

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#101] opened 2018-06-11 10:46 UTC
As per document ref_formatting.xls (dated 11 June, by email) , this now supersedes #60 which is closed.

**Comment by nomoregrapes** [comment] 2018-06-14 15:55
Collection of examples we can use to check...
* [ref3](http://10.245.28.108:3000/references/ref3) - book:monograph
* [ref62](http://10.245.28.108:3000/references/ref62) - book with more values
* [ref20](http://10.245.28.108:3000/references/ref20) - book chapter
* [ref200](http://10.245.28.108:3000/references/ref200) - letter 
* [ref9](http://10.245.28.108:3000/references/ref9) - periodical
* Poem?

**Comment by nomoregrapes** [comment] 2018-06-14 16:01
This is done, all rules met. I think it will need the latest annotation versions added to demonstrate all the fields. See my previous comment for some links to examples, and what journals you can find the annotations in.

Personally I think it would be nicer for some vertical spacing to be used. The annotation popups should also perhaps have the title in bold, so it matches other popups?

**Comment by peterwebster** [comment] 2018-06-19 08:49
Hi @nomoregrapes :  @DurHHHI is very close indeed to having a final version of ref.tsv. Would you like this sooner rather than later for testing?

**Comment by nomoregrapes** [comment] 2018-06-20 12:47
I'm already happy enough that it works as intended.
I'm distracted by the Solr downgrade at the moment, so wouldn't be ingesting a new ref.tsv unless you're really wanting to test newer examples.

**Comment by peterwebster** [comment] 2018-06-20 13:44
We've had a look at the examples, but I think we will need to see how it looks with the updated data; but not right now..

**Comment by peterwebster** [comment] 2018-07-19 10:09
Hi @DurHHHI : apart from the specific matter in #98 , are you satisfied that the GUI picks up all the right fields for refs, and displays them in the right order, correctly punctuated etc.?

**Comment by DurHHHI** [comment] 2018-07-20 11:19
@peterwebster -I'm working through this

ref9 - periodical - is displaying as:
<img width="1188" alt="screen shot 2018-07-20 at 12 17 58 pm" src="https://user-images.githubusercontent.com/32575577/42999824-1c24b81a-8c17-11e8-9aec-6e46a0893787.png">

It is missing the year - 
Should be displayed as:
H. H. Henson, 'Our unhappy divisions: a plea for the recognition of non-episcopal churches', _Contemporary Review_, 80 (1901), 794-805.

**Comment by DurHHHI** [comment] 2018-07-20 11:23
@peterwebster 

Issue with ref200 - letter - above, as well. Currently displaying as:

<img width="1053" alt="screen shot 2018-07-20 at 12 23 38 pm" src="https://user-images.githubusercontent.com/32575577/43000045-da1aaeba-8c17-11e8-9b12-0b5a4cb9f87a.png">

Missing date/year: Should be:

H. H. Henson, et al., letter, 'The bishop of Birmingham and Canon Henson', _Times_, 2 Apr. 1909, 10.

**Comment by DurHHHI** [comment] 2018-07-20 11:26
@peterwebster 

Another issue with ref20 - book chapter, from above examples. Currently displaying as:

<img width="1209" alt="screen shot 2018-07-20 at 12 25 09 pm" src="https://user-images.githubusercontent.com/32575577/43000115-199b305a-8c18-11e8-9b05-110b7c8ca0b2.png">

Missing year and title and editor in wrong order. Should be reflected as:

H. H. Henson, 'Jeremy Taylor', in _Typical English churchmen from Parker to Maurice: a series of lectures_, ed. William Edward Collins (London, 1902).

**Comment by DurHHHI** [comment] 2018-07-20 11:34
@peterwebster 

ref62 - book with more values - is also missing year. Displaying as:
<img width="1171" alt="screen shot 2018-07-20 at 12 31 39 pm" src="https://user-images.githubusercontent.com/32575577/43000378-18d6109e-8c19-11e8-8c1f-c3eee4191769.png">

Should be:
Adolf Harnack, _The expansion of christianity in the first three centuries_, ed. and trans. James Moffat (2 vols, London, 1904-05).

**Comment by DurHHHI** [comment] 2018-07-20 11:37
@peterwebster 

Finally, ref3 - book:monograph - also displaying incorrectly:

2 vols listed twice (appearance twice might be an input issue with '2 vols' appearing in 'title' field - if so, will fix in TSV) and publication missing year.

<img width="1096" alt="screen shot 2018-07-20 at 12 34 10 pm" src="https://user-images.githubusercontent.com/32575577/43000438-54209638-8c19-11e8-97a1-c0c49f5c9656.png">

Should be reflected as: 
James Boswell, _The life of Samuel Johnson, LL.D._ (2 vols, London, 1791).

**Comment by DurHHHI** [comment] 2018-07-20 11:43
@peterwebster No surprise I'm sure given above examples, but in search, confirmation that all references missing date/year necessary field.

**Comment by peterwebster** [comment] 2018-07-23 14:34
These look to be several different presentation of the same issue @nomoregrapes

**Comment by DurHHHI** [comment] 2018-07-23 15:08
@peterwebster - yes, save for the book chapter example - missing year and in different order.

**Comment by nomoregrapes** [comment] 2018-08-08 10:22
This was actually an ingest issue, none of the dates were in the database. Not sure why we didn't spot that sooner, but all fixed now.

[ref9](http://10.245.28.108:3000/references/ref9), [ref200](http://10.245.28.108:3000/references/ref200), [ref20](http://10.245.28.108:3000/references/ref20), [ref62](http://10.245.28.108:3000/references/ref62), [ref3](http://10.245.28.108:3000/references/ref3)

**Comment by peterwebster** [comment] 2018-08-08 10:50
@DurHHHI if you're happy with this, do close this one down.

**Closed as completed** 2018-08-15 12:37 UTC
Labels: critical
