### ISSUE TITLE
No website access on Edge

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#128] opened 2018-07-02 13:45 UTC
Gregory, just so you know and can look into it, the website doesn't seem to be accessible at all using Edge.

**Comment by nomoregrapes** [comment] 2018-07-02 16:00
Errr, could you try again?
Hoping you didn't catch it while I was doing a restart.

**Comment by KPalmerHeathman** [comment] 2018-07-03 09:11
Still no.

**Comment by nomoregrapes** [comment] 2018-07-06 13:45
Problem confirmed. Can't fix myself, going to assume I've found the correct reason...

The website (probably) works fine, but Microsoft doesn't like that the address is an IP address on the network (i.e. my laptop could be running a dodgy scam website). This will not be an issue when we have the website setup in a way that the whole world(& Peter) can view.

There is a meanwhile-fix, but I don't have permission on the university computer to do it myself. If you have your own windows laptop, you could (1st check it's not working on that) go to control panel and [follow the top answer here](https://social.technet.microsoft.com/Forums/en-US/0face535-3c7a-4658-be34-6c376322ca34/microsoft-edge-cant-open-local-domains). Close Microsoft Edge, reopen it, test the website.
If you confirm that fixes it, then you might want to return and tick those boxes again to put your security back. Or be careful and don't go to websites if the address is strange (especially on public/shared wifi).


@peterwebster do we want to close this ticket, because the issue will fix itself? Or do we want to keep it open so we remember to check Microsoft Edge?

**Comment by peterwebster** [comment] 2018-07-06 13:47
Let's close it @KPalmerHeathman @nomoregrapes

**Closed as completed by peterwebster** 2018-07-06 13:47 UTC
